### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by digitaldreamd** [dreamcat4/Mcp4261#1]
Cannot compile in both 1.0.3 and 1.5.2.
In file included from Mcp4261Example.pde:12:

D:\sketchbook\libraries\Mcp4261/Mcp4261.h:12: error: expected `)' before 'slave_select'
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:15: error: expected`)' before 'slave_select'
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:63: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:65: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:66: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:68: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:69: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:71: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:72: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:74: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:75: error: 'uint8_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:77: error: 'uint16_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:78: error: 'byte' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:79: error: 'byte' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:81: error: 'uint8_t' has not been declared
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:88: error: 'uint16_t' does not name a type
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:89: error: 'byte' has not been declared
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:89: error: 'byte' has not been declared
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:90: error: 'byte' has not been declared
Mcp4261Example:27: error: no matching function for call to 'MCP4261::MCP4261(int, float&)'
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:9: note: candidates are: MCP4261::MCP4261()
D:\sketchbook\libraries\Mcp4261/Mcp4261.h:9: note:                 MCP4261::MCP4261(const MCP4261&)
